### ISSUE TITLE
Always shows error!

### ISSUE THREAD

**Issue by sandrocottus** [Rustensic/thumbsdbkit#1]
I've tried multiple files but whenever I try to use this tool, it throws the following error:
```
An error has occured: This file doesn't seem to be a Thumbs.db

```

**Comment by zadlg** [comment]
Hi @sandrocottus,

Can you provide one of the files you tried ? I'll look on it, and fix the issue.

**Comment by sandrocottus** [comment]
http://w3.saj.usace.army.mil/h2o/reports/Thumbs.db

**Comment by zadlg** [comment]
Okay, so your file isn't a XP _Thumbs.db_ : there is no _Catalog_ entry inside. It looks like it's a _Thumbs.db_ from a Windows Vista or 7.
According to the [ForensicsWiki page on Thumbs.db](https://www.forensicswiki.org/wiki/Thumbs.db):
```
The format is still an OLE container but without the Catalog stream and with a few other changes. 
```

I'll modify the [lib thumbsdb](https://github.com/Rustensic/thumbsdb) for supporting Windows Vista et Windows 7.

However, you can use [https://github.com/Rustensic/olekit](olekit) which does basically the same as _thumbsdbkit_. It works with your _Thumbs.db_ !

**Comment by sandrocottus** [comment]
Thanks it worked! Can you help me extracting thumbnails in a readable format? I tried exporting images with jpeg, jpg, gif and bmp extensions but none seems to work.
